### ISSUE TITLE
Switch config file format from INI to JSON

### ISSUE THREAD

**Issue by jctophefabre** [OpenFLUID/openfluid#1040]
## guidelines

* compatibility is kept with existing INI files, they are automatically transformed to JSON files at first use. 
* boost::property_tree will be used to read existing INI files
* RapidJSOn will be used to store the configuration data
* Ability to store QVariant data (such as QPoint, ...) will be kept

## File names

* `openfluid.conf` -> `openfluid-setting.json`
* `openfluid-waresdev.conf` -> `openfluid-workspace.json`
* `openfluid-project.conf` -> `openfluid-project.json`
* `ofwdp.conf` -> `openfluid-wares-package.json`

## TODO

- [ ] Create a generic ConfigurationManager class to manage a configuration dataset including 
    * backwards fomat compatibility
    * in/out methods with hierachical location for values
- [ ] Implement the ConfigurationManager class as the configuration engine for PreferencesManager
- [ ] Implement the ConfigurationManager class as the configuration engine for RunContextManager
- [ ] Implement the ConfigurationManager class as the configuration engine for DevStudioPreferencesManager
- [ ] Implement the ConfigurationManager class as the configuration engine for WaresDevPackage
