### ISSUE TITLE
Apps manual testing

### ISSUE THREAD

**Issue by Arthoni** [OpenFLUID/openfluid#1178]
Check if working as intended and efficiency of UX

# Initial
## DevStudio
- [-] Ware signature (cf #1038)
    - [x] Standard signature
    - [-] Template signature (cf #1157)
- [x] Code fragments (cf #928 )
- [x] Global UI changes (#1017, #1127, #1095, #1078)

## Builder
- [x] Converting ghost to real simulator
- [x] Multicolumn generators  (cf #1030, #306)

## CLI
- [x] Run each command with various args

# Beta-testing
- [x] Build dedicated matrix to check features on several versions of Linux and Windows
