### ISSUE TITLE
Create wares source tree using a skeleton with templates

### ISSUE THREAD

**Issue by jctophefabre** [OpenFLUID/openfluid#717]
Example of a ware source tree
```
\ example.ware.struct
  - wareinfo.json
  - CMakeLists.txt
  - README.md
  - LICENSE
  \ src
    - WareMain.cpp
    - CMakeLists.txt
    - build-config.cmake
  \ doc
  \ tests
```

## Tasks

- [x] common skeleton
- [x] simulator specific skeleton
- [x] observer specific skeleton
- [x] builderext specific skeleton
- [x] creation process from skeleton(s)
- [x] adapt cmake processes and modules
